package com.example.todoapp.dto;

/**
 * DTO for POST /tasks request body.
 * id is auto-generated by SQLite; done is initialized to false.
 */
public class TaskCreateDto {

    private String title;
    private String description;

    public TaskCreateDto() {
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
