package com.example.todoapp.service;

import com.example.todoapp.dao.TaskDao;
import com.example.todoapp.dto.TaskCreateDto;
import com.example.todoapp.dto.TaskResponseDto;
import com.example.todoapp.dto.TaskUpdateDto;
import com.example.todoapp.model.Task;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Business logic layer for task operations.
 */
public class TaskService {

    private static final Logger log = LoggerFactory.getLogger(TaskService.class);

    private final TaskDao taskDao;

    public TaskService(TaskDao taskDao) {
        this.taskDao = taskDao;
    }

    /**
     * Retrieve all tasks, optionally filtered to incomplete ones.
     *
     * @param todoOnly if true, only return tasks where done=false
     * @return list of task response DTOs
     */
    public List<TaskResponseDto> getAllTasks(boolean todoOnly) {
        List<Task> tasks = todoOnly ? taskDao.findAllTodo() : taskDao.findAll();
        log.debug("getAllTasks todoOnly={} count={}", todoOnly, tasks.size());
        return tasks.stream().map(this::toResponseDto).collect(Collectors.toList());
    }

    /**
     * Retrieve a single task by id.
     *
     * @param id task identifier
     * @return optional DTO, empty if not found
     */
    public Optional<TaskResponseDto> getTaskById(int id) {
        return taskDao.findById(id).map(this::toResponseDto);
    }

    /**
     * Create a new task from the given DTO.
     * done is set to false and id is generated by the database.
     *
     * @param dto create request DTO
     * @return the created task as a response DTO
     */
    public TaskResponseDto createTask(TaskCreateDto dto) {
        Task task = new Task(null, dto.getTitle(), dto.getDescription(), false);
        Task created = taskDao.insert(task);
        log.info("Task created id={}", created.id());
        return toResponseDto(created);
    }

    /**
     * Update an existing task.
     *
     * @param id  identifier of the task to update
     * @param dto update request DTO
     * @return true if found and updated, false if not found
     */
    public boolean updateTask(int id, TaskUpdateDto dto) {
        Task task = new Task(id, dto.getTitle(), dto.getDescription(), dto.isDone());
        return taskDao.update(task);
    }

    /**
     * Delete a task by id.
     *
     * @param id task identifier
     * @return true if found and deleted, false if not found
     */
    public boolean deleteTask(int id) {
        return taskDao.delete(id);
    }

    private TaskResponseDto toResponseDto(Task task) {
        return new TaskResponseDto(task.id(), task.title(), task.description(), task.done());
    }
}
